name: binstall

on: [push, pull_request]

permissions: {}

jobs:
  binstall:
    if: github.repository == 'Swatinem/rust-cache'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Test `cargo binstall` on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: cargo-bins/cargo-binstall@ead08b90bd7b2e6d81963fb9cf0b7239f66d5db4 # v1.21.0

      - uses: ./

      - run: cargo binstall -y cargo-deny
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
