name: blacksmith

on: [push, pull_request]

jobs:
  blacksmith:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Test blacksmith provider on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v3

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: ./
        with:
          workspaces: tests
          cache-provider: blacksmith

      - run: |
          cargo check
          cargo test
          cargo build --release
        working-directory: tests
