name: coverage

on: [push, pull_request]

permissions: {}

jobs:
  coverage:
    if: github.repository == 'Swatinem/rust-cache'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Test `cargo-llvm-cov` on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - run: rustup toolchain install stable --profile minimal --component llvm-tools-preview --no-self-update

      - uses: taiki-e/install-action@a6b2e2dcd845ddd7f509ce4f3ed3d922b80cc5d9 # v2.84.0
        with:
          tool: cargo-llvm-cov

      - uses: ./
        with:
          workspaces: tests

      - run: cargo llvm-cov --all-features --workspace
        working-directory: tests
