name: nix

on: [push, pull_request]

permissions: {}

jobs:
  nix:
    if: github.repository == 'Swatinem/rust-cache'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    name: Test Nix on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@96951a368ba55167b55f1c916f7d416bac6505fe # v31.10.3

      - uses: ./
        with:
          workspaces: tests
          cmd-format: nix develop ./tests -c {0}

      - run: |
          nix develop -c cargo check
          nix develop -c cargo test
        working-directory: tests
